# Generated by Django 4.2.4 on 2023-08-21 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_portfolio_name', models.CharField(default='Portfolio', max_length=20)),
                ('stock_portfolio_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_name', models.CharField(max_length=50)),
                ('investment_type', models.CharField(max_length=20)),
                ('investment_ticker', models.CharField(max_length=20)),
                ('investment_units', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('investment_to_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockportfolio.stockportfolio')),
            ],
        ),
    ]
